version: '3.8'

services:
  backend:
    build: ./backend
    ports: ["8000:8000"]
    volumes:
      - ./models:/app/models
    env_file: .env
    depends_on: [redis]

  frontend:
    build: ./frontend
    ports: ["3000:3000"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on: [backend]

  redis:
    image: redis:alpine
    ports: ["6379:6379"]
    volumes: [redis_data:/data]

volumes: [redis_data]